services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: venue
      POSTGRES_USER: venue
      POSTGRES_PASSWORD: venue
