services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: venue
      POSTGRES_PASSWORD: password
    volumes:
      - "./modules/server/resources/db/migrations:/docker-entrypoint-initdb.d:ro"
    ports:
      - 5432:5432

  statics:
    image: nginx:1-alpine
    restart: always
    volumes:
      - "./modules/development-statics:/usr/share/nginx/html:ro"
    ports:
      - 8001:80
