services:
  db:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_USER: venue
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  statics:
    image: nginx:1
    restart: always
    volumes:
      - "./modules/development-statics:/usr/share/nginx/html:ro"
    ports:
      - 0.0.0.0:8001:80
